---
hosts: all
become: true
remote_user: root

tasks:
- name: Ensure apache is at its latest version
  ansible.builtin.yum
     name: httpd
     state: latest

- name: Write apache config file
  ansible.builtin.tempalate:
    src: /srv/httpd.j2
    dest: /etc/httpd.conf

- name: Update db servers
  hosts: databases
  remote_user: root

  tasks:
  - name: Ensure postgresql is at its latest version
    ansible.builtin.yum:
     name: postgresql
     state: latest

  - name: Ensure that postgresql is started
    ansible.builtin.service:
     name: postgresql
     sate: latest


